/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class telaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form telaCalculadora
     */
    public telaCalculadora() {
        initComponents();
        panInfo.setVisible(false);
    }
    
  
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSalario = new javax.swing.JTextField();
        lblCarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblHe1 = new javax.swing.JTextField();
        checkHe1 = new javax.swing.JCheckBox();
        checkAd1 = new javax.swing.JCheckBox();
        btnCalc = new javax.swing.JButton();
        panInfo = new javax.swing.JPanel();
        lblValHora = new javax.swing.JLabel();
        lblHeMes = new javax.swing.JLabel();
        lblInss = new javax.swing.JLabel();
        lblIrpf = new javax.swing.JLabel();
        lblBruto = new javax.swing.JLabel();
        lblLiquido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblHe2 = new javax.swing.JTextField();
        checkAd2 = new javax.swing.JCheckBox();
        checkHe2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        lblHe3 = new javax.swing.JTextField();
        checkAd3 = new javax.swing.JCheckBox();
        checkHe3 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        lblHe4 = new javax.swing.JTextField();
        checkAd4 = new javax.swing.JCheckBox();
        checkHe4 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Qual seu salário Atual?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Qual sua carga horária semanal?");

        jLabel3.setText("Hora Extra");

        lblHe1.setText("0");

        checkHe1.setText("100%");

        checkAd1.setText("Ad. Noturno");

        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        lblValHora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblValHora.setForeground(new java.awt.Color(51, 51, 255));

        lblHeMes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHeMes.setForeground(new java.awt.Color(51, 51, 255));

        lblInss.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblInss.setForeground(new java.awt.Color(51, 51, 255));

        lblIrpf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIrpf.setForeground(new java.awt.Color(51, 51, 255));

        lblBruto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBruto.setForeground(new java.awt.Color(51, 51, 255));

        lblLiquido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLiquido.setForeground(new java.awt.Color(51, 51, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Valor/Hora:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("HE/Mês:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("INSS:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("IRPF:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Bruto:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Líquido:");

        javax.swing.GroupLayout panInfoLayout = new javax.swing.GroupLayout(panInfo);
        panInfo.setLayout(panInfoLayout);
        panInfoLayout.setHorizontalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInfoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblValHora))
                    .addGroup(panInfoLayout.createSequentialGroup()
                        .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(39, 39, 39)
                        .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeMes)
                            .addComponent(lblInss)
                            .addComponent(lblIrpf)
                            .addComponent(lblBruto)
                            .addComponent(lblLiquido))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panInfoLayout.setVerticalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblValHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeMes)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblInss))
                .addGap(10, 10, 10)
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblIrpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBruto)
                    .addComponent(jLabel8))
                .addGap(14, 14, 14)
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblLiquido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblHe2.setText("0");

        checkAd2.setText("Ad. Noturno");

        checkHe2.setText("100%");

        jLabel10.setText("Hora Extra");

        lblHe3.setText("0");

        checkAd3.setText("Ad. Noturno");

        checkHe3.setText("100%");

        jLabel11.setText("Hora Extra");

        lblHe4.setText("0");

        checkAd4.setText("Ad. Noturno");

        checkHe4.setText("100%");

        jLabel12.setText("Hora Extra");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setText("(Ex: 1000.00)");

        jLabel14.setText("R$");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel15.setText("(Ex: 20, 40, 44)");

        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Desenvolvido por Artenir Pinho");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHe3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkHe3)
                                .addGap(18, 18, 18)
                                .addComponent(checkAd3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHe1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkHe1)
                                .addGap(18, 18, 18)
                                .addComponent(checkAd1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHe2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkHe2)
                                .addGap(18, 18, 18)
                                .addComponent(checkAd2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHe4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkHe4)
                                .addGap(18, 18, 18)
                                .addComponent(checkAd4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(btnCalc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblHe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkHe1)
                    .addComponent(checkAd1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblHe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkHe2)
                    .addComponent(checkAd2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblHe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkHe3)
                    .addComponent(checkAd3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblHe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkHe4)
                    .addComponent(checkAd4))
                .addGap(18, 18, 18)
                .addComponent(btnCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        panInfo.setVisible(true);
         
       // JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente!", "AVISO", 1);
       
     
        
        //INFORMACOES
        float salario = Float.parseFloat(lblSalario.getText());
        int carga = Integer.parseInt(lblCarga.getText());
        int he1 = Integer.parseInt(lblHe1.getText());
        int he2 = Integer.parseInt(lblHe2.getText());
        int he3 = Integer.parseInt(lblHe3.getText());
        int he4 = Integer.parseInt(lblHe4.getText());
        float tothoras = carga * 4;
        float horatrab = salario / tothoras;
        
                
        //CALCULO HE
        double mult1 = 1.5;
        if(checkHe1.isSelected()){
            mult1 += 0.5;
        }        if(checkAd1.isSelected()){
                     mult1 += 0.2;
        }
        
        double mult2 = 1.5;
        if(checkHe2.isSelected()){
            mult2 += 0.5;
        }        if(checkAd2.isSelected()){
                     mult2 += 0.2;
        }
        
        double mult3 = 1.5;
        if(checkHe3.isSelected()){
            mult3 += 0.5;
        }        if(checkAd3.isSelected()){
                    mult3 += 0.2;
        }   
        
        double mult4 = 1.5;
        if(checkHe4.isSelected()){
            mult4 += 0.5;
                 if(checkAd4.isSelected()){
                     mult4 += 0.2;
                 }
        }
        //RESULTADOS
        double calche1 = (he1 * horatrab) * mult1;
        double calche2 = (he2 * horatrab) * mult2;
        double calche3 = (he3 * horatrab) * mult3;
        double calche4 = (he4 * horatrab) * mult4;
        double tothe = (calche1 + calche2 + calche3 + calche4);
        double somahe = salario + tothe;
        
        //INSS
        double inss = 0;
        if (somahe <= 1100){
            inss = 7.5;
        }   else if (somahe >= 1101 && somahe <= 2203){
                inss = 9.0;
        }       else if (somahe >= 2204 && somahe <= 3305){
                    inss = 12.0;
        }           else {
                        inss = 14.0;
        }
        double calcInss = (somahe * inss) / 100;
        lblInss.setText("Alíquota de " + inss + "% e desconto de " + (String.format("%.2f", calcInss)));
        
        //IRPF
        double irpf = 0;
        if (somahe <= 1903){
            irpf = 0;
        }   else if (somahe >= 1904 && somahe <= 2826){
                irpf = 7.5;
        }       else if (somahe >= 2827 && somahe <= 3751){
                    irpf = 15.0;
        }           else if (somahe >= 3752 && somahe <= 4664){
                        irpf = 22.5;
        }               else {
                            irpf = 27.70;
        }
        double calcIrpf = (somahe * irpf) / 100;
        lblIrpf.setText("Alíquota de " + irpf + "% e desconto de " + (String.format("%.2f", calcIrpf)));
        
        //PAINEL
        double liquido = somahe - calcInss - calcIrpf;
        lblValHora.setText(String.format("O valor da sua hora trabalhada é de R$ " + "%.2f", horatrab));
        lblHeMes.setText(String.format("Suas horas extras no mês são R$ " + "%.2f", tothe));
        lblBruto.setText(String.format("Seu salário Bruto é R$" + "%.2f", somahe));
        lblLiquido.setText(String.format("Seu salário Líquido é de R$" + "%.2f", liquido));   
        
             
        
    }//GEN-LAST:event_btnCalcActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JCheckBox checkAd1;
    private javax.swing.JCheckBox checkAd2;
    private javax.swing.JCheckBox checkAd3;
    private javax.swing.JCheckBox checkAd4;
    private javax.swing.JCheckBox checkHe1;
    private javax.swing.JCheckBox checkHe2;
    private javax.swing.JCheckBox checkHe3;
    private javax.swing.JCheckBox checkHe4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBruto;
    private javax.swing.JTextField lblCarga;
    private javax.swing.JTextField lblHe1;
    private javax.swing.JTextField lblHe2;
    private javax.swing.JTextField lblHe3;
    private javax.swing.JTextField lblHe4;
    private javax.swing.JLabel lblHeMes;
    private javax.swing.JLabel lblInss;
    private javax.swing.JLabel lblIrpf;
    private javax.swing.JLabel lblLiquido;
    private javax.swing.JTextField lblSalario;
    private javax.swing.JLabel lblValHora;
    private javax.swing.JPanel panInfo;
    // End of variables declaration//GEN-END:variables
}
